# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20170415_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_empresa',
            field=models.CharField(max_length=255),
        ),
    ]
