# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20170416_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_empresa',
            field=models.CharField(max_length=50),
        ),
    ]
